"""users table add confirmed status

Revision ID: 5a7ce51d6929
Revises: 8ac5a1a89d78
Create Date: 2021-02-07 11:18:36.253183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7ce51d6929'
down_revision = '8ac5a1a89d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmed')
    # op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###
